version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./bd.json:/app/bd.json
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
