#Practica 2
version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./bd.json:/app/bd.json

