version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app
    ports:
      - "4000:4000" # Mapea el puerto 4000 del contenedor al puerto 4000 del host
    environment:
      - NODE_ENV=production
    volumes:
      - ./bd.json:/app/bd.json

